### ISSUE TITLE
Subtitle loading issue

### ISSUE THREAD

**Issue by MohgaNabil** [brightcove/brightcove-player-sdk-ios-sidecarsubtitles#2]
Hi
I can't get the subtitles to show up if I'm constructing the video instance manually and not through the playback service.  I think there might be a property or something that the playback service sets or does that I don't and I have to do it myself in that case.

Appreciate your help, Thanks :) 

p.s: I've tested this code with a video fetched using the playback service and the subtitles work fine.

<img width="979" alt="screen shot 2017-02-19 at 6 07 14 pm" src="https://cloud.githubusercontent.com/assets/12371520/23104044/a7152732-f6ce-11e6-93a9-73e00d5dabdb.png">

**Comment by sjbushell** [comment]
Sidecar Subtitles only work with videos in HLS format, not MP4 like you have listed in your sample code. There's no simple way to add subtitles to an MP4 because they don't have anything like the HLS manifest where subtitles are referenced.

So, rather than using a local MP4 file, you need to host your custom HLS file somewhere (you can't just play HLS straight from storage) or simply ingest it into your Video Cloud account.

I'll make a note to update the README with the fact that this plugin only works with HLS.
